name: ETL Pipeline Testing with PySpark

on:
  push:
    branches: [ "main", "ci/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  etl-tests:
    name: Run ETL Tests with PySpark
    runs-on: aexp-ubuntu-latest-medium

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

      - name: Verify Java Installation
        run: java -version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          

      - name: Install Python Dependencies
        run: pip install -r requirements.txt || pip install -r requirements.txt

      - name: Verify Data Files
        run: ls -al data/

      - name: Run ETL Tests for Config1
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python run_tests/run_test_config1.py
