name: ETL Pipeline Testing with PySpark

on:
  push:
    branches:
      - "main"
      - "ci/*"
  pull_request:
    branches:
      - "main"

jobs:
  etl-tests:
    name: Run ETL Tests with PySpark
    runs-on: aexp-ubuntu-latest-medium

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Identify Affected Tests
        id: identify-affected-tests
        run: python mapper.py

      - name: Run Tests for Affected Tables
        if: steps.identify-affected-tests.outcome == 'success'
        run: |
          echo "Running affected tests..."
          while IFS= read -r test_file; do
            echo "Running: $test_file"
            python "$test_file"
          done < affected_tests.txt
